### ISSUE TITLE
bug using QRcode in laravel 5.5

### ISSUE THREAD

**Issue by ylapin** [milon/barcode#178]
**this is  a general error and it's not important which number I put always the same error
also it's a problem because I wanted to encode a url, not a number but anyway it's not working**

production.ERROR: imagecreate(): Invalid image dimensions {"exception":"[object] (ErrorException(code: 0): imagecreate(): Invalid image dimensions at /projects/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php:171)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'imagecreate(): ...', '/projec...', 171, Array)
#1 /projects/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php(171): imagecreate(0, 30)
#2 /projects/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php(2456): Milon\\Barcode\\DNS1D->getBarcodePNG('438436', 'QRCODE')
#3 /projects/app/Library/functions.php(278): Milon\\Barcode\\DNS1D::__callStatic('getBarcodePNG', Array)

**Comment by milon** [comment]
`imagecreate(): Invalid image dimensions` usually means encoding failed (empty/invalid payload or failed QR build) and the library proceeded with a zero-size image.

Current versions throw `InvalidBarcodeException` instead. Please upgrade, ensure GD is installed, and use a non-empty string/URL. For dark backgrounds pass a white `$bgcolor`.

Closing as addressed by validation + docs; reopen with a minimal sample on a current version if needed.
